### ISSUE TITLE
Test fleet setup

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-go-waku#1]
Create `go-waku.test` fleet to figure out proper setup.

**Comment by jakubgs** [comment]
Original work to create repo and deploy fleet:

- https://github.com/status-im/infra-go-waku/commit/57d25321 - add gitignore
- https://github.com/status-im/infra-go-waku/commit/0d091e21 - add readme
- https://github.com/status-im/infra-go-waku/commit/7feffc68 - bootstrap terraform configuration
- https://github.com/status-im/infra-go-waku/commit/34c4dbc8 - bootstrap ansible configuration
- https://github.com/status-im/infra-go-waku/commit/af8a17c3 - add Makefile to fetch plugins and secrets
- https://github.com/status-im/infra-go-waku/commit/3435cdcb - add hosts configuration
- https://github.com/status-im/infra-go-waku/commit/8784078d - initialize test fleet inventory
- https://github.com/status-im/infra-go-waku/commit/132c45f6 - add initial main playbook
- https://github.com/status-im/infra-go-waku/commit/bcd65a5e - go-waku: init of Ansible role
- https://github.com/status-im/infra-go-waku/commit/354646f0 - deploy go-waku to test nodes

Opened some issues:

- https://github.com/status-im/go-waku/issues/80
- https://github.com/status-im/go-waku/issues/81
- https://github.com/status-im/go-waku/issues/82
- https://github.com/status-im/nim-waku/issues/743

Also made some adjustments to `go-waku` repo:

- https://github.com/status-im/go-waku/pull/83
- https://github.com/status-im/go-waku/pull/84

**Comment by jakubgs** [comment]
Adjustments to configuration:

- https://github.com/status-im/infra-go-waku/commit/f53b6d51 - go-waku: set GOLOG_LOG_FMT=json for parseable logs
- https://github.com/status-im/infra-go-waku/commit/7129242a - go-waku: use --show-addresses to save multiaddr
- https://github.com/status-im/infra-go-waku/commit/b06b5148 - go-waku: use --advertise-address flag
- https://github.com/status-im/infra-go-waku/commit/ceca6708 - go-waku: add basic readme
- https://github.com/status-im/infra-go-waku/commit/df796151 - go-waku: use --use-db by default
- https://github.com/status-im/infra-go-waku/commit/772d3ed3 - go-waku: enable --rendezvous-server
- https://github.com/status-im/infra-go-waku/commit/ef14333e - go-waku: fix --dbpath flag value
- https://github.com/status-im/infra-go-waku/commit/9dc00a10 - go-waku: add discovery of other nodes in the fleet
- https://github.com/status-im/infra-go-waku/commit/d113ef39 - go-waku: separate env and stage in consul tags

And adjustment to `nim-waku` fleet to make more exact consul queries possible:

- https://github.com/status-im/infra-nim-waku/commit/b922d149 - nim-waku: separate env and stage in consul tags

**Comment by jakubgs** [comment]
At request from @richard-ramos I've also added static connection to `wakuv2.test` fleet peers: https://github.com/status-im/infra-go-waku/commit/2f85a7e3
```
 > a all -a 'docker inspect go-waku-node | jq ".[].Config.Cmd"'
node-01.do-ams3.go-waku.test | CHANGED | rc=0 >>
[
  "--nodekey=",
  "--log-level=INFO",
  "--port=30303",
  "--advertise-address=134.209.134.63",
  "--use-db",
  "--dbpath=/data/store.db",
  "--rendezvous-server",
  "--rendezvous-db-path=/data/rendezvous",
  "--metrics",
  "--metrics-port=8008",
  "--metrics-address=0.0.0.0",
  "--static-node=/ip4/8.218.2.110/tcp/9000/p2p/QmSQwfZ2Vzdeh1jUSGnbGvHDDAHaGhcymrXjdkSWMrqqvm",
  "--static-node=/ip4/35.223.183.91/tcp/9000/p2p/QmTDQKMPCFha3Ug8DUjmoMW4yGcNipWuUzVKbzrb3e4avz",
  "--static-node=/ip4/134.209.134.63/tcp/9000/p2p/QmSqdLXgfxBZaDUmaRN2oXE23miE6xVcrh4x3A65Gd2cGV",
  "--static-node=/ip4/47.242.210.73/tcp/30303/p2p/16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm",
  "--static-node=/ip4/104.154.239.128/tcp/30303/p2p/16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS",
  "--static-node=/ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ"
]
node-01.gc-us-central1-a.go-waku.test | CHANGED | rc=0 >>
[
  "--nodekey=",
  "--log-level=INFO",
  "--port=30303",
  "--advertise-address=35.223.183.91",
  "--use-db",
  "--dbpath=/data/store.db",
  "--rendezvous-server",
  "--rendezvous-db-path=/data/rendezvous",
  "--metrics",
  "--metrics-port=8008",
  "--metrics-address=0.0.0.0",
  "--static-node=/ip4/8.218.2.110/tcp/9000/p2p/QmSQwfZ2Vzdeh1jUSGnbGvHDDAHaGhcymrXjdkSWMrqqvm",
  "--static-node=/ip4/35.223.183.91/tcp/9000/p2p/QmTDQKMPCFha3Ug8DUjmoMW4yGcNipWuUzVKbzrb3e4avz",
  "--static-node=/ip4/134.209.134.63/tcp/9000/p2p/QmSqdLXgfxBZaDUmaRN2oXE23miE6xVcrh4x3A65Gd2cGV",
  "--static-node=/ip4/47.242.210.73/tcp/30303/p2p/16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm",
  "--static-node=/ip4/104.154.239.128/tcp/30303/p2p/16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS",
  "--static-node=/ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ"
]
node-01.ac-cn-hongkong-c.go-waku.test | CHANGED | rc=0 >>
[
  "--nodekey=",
  "--log-level=INFO",
  "--port=30303",
  "--advertise-address=8.218.2.110",
  "--use-db",
  "--dbpath=/data/store.db",
  "--rendezvous-server",
  "--rendezvous-db-path=/data/rendezvous",
  "--metrics",
  "--metrics-port=8008",
  "--metrics-address=0.0.0.0",
  "--static-node=/ip4/8.218.2.110/tcp/9000/p2p/QmSQwfZ2Vzdeh1jUSGnbGvHDDAHaGhcymrXjdkSWMrqqvm",
  "--static-node=/ip4/35.223.183.91/tcp/9000/p2p/QmTDQKMPCFha3Ug8DUjmoMW4yGcNipWuUzVKbzrb3e4avz",
  "--static-node=/ip4/134.209.134.63/tcp/9000/p2p/QmSqdLXgfxBZaDUmaRN2oXE23miE6xVcrh4x3A65Gd2cGV",
  "--static-node=/ip4/47.242.210.73/tcp/30303/p2p/16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm",
  "--static-node=/ip4/104.154.239.128/tcp/30303/p2p/16Uiu2HAmJb2e28qLXxT5kZxVUUoJt72EMzNGXB47Rxx5hw3q4YjS",
  "--static-node=/ip4/134.209.139.210/tcp/30303/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ"
]
```

**Comment by jakubgs** [comment]
We had a weird discrepancy in public key formats between `go-waku` and `nim-waku` but @richard-ramos fixed it:

- https://github.com/status-im/go-waku/commit/b661a4b9 - fix: missing identity

**Comment by jakubgs** [comment]
Refactored how we query services buy using [`filter`]() queries:

- https://github.com/status-im/infra-go-waku/commit/18888a22 - go-waku: query using NodeMeta instead of tags
- https://github.com/status-im/infra-misc/commit/129ca330 - status-fleets: query using new filter and NodeMeta
- https://github.com/status-im/infra-eth-cluster/commit/b70f9454 - query Consul using NodeMeta instead of tags

**Comment by jakubgs** [comment]
Now we can find it at https://fleets.status.im/
```
 > curl -sSL fleets.status.im | jq '.fleets."go-waku.test"'
{
  "go-waku": {
    "node-01.ac-cn-hongkong-c.go-waku.test": "/ip4/8.218.2.110/tcp/9000/p2p/16Uiu2HAmBDbMWFiG9ki8sDw6fYtraSxo4oHU9HbuN43S2HVyq1FD",
    "node-01.do-ams3.go-waku.test": "/ip4/134.209.134.63/tcp/9000/p2p/16Uiu2HAm9vnvCQgCDrynDK1h7GJoEZVGvnuzq84RyDQ3DEdXmcX7",
    "node-01.gc-us-central1-a.go-waku.test": "/ip4/35.223.183.91/tcp/9000/p2p/16Uiu2HAmPz63Xc6AuVkDeujz7YeZta18rcdau3Y1BzaxKAfDrBqz"
  }
}
```

**Comment by D4nte** [comment]
Any chance we could enable websocket too? I believe it's supported natively but not sure how SSL is handled.

cc @richard-ramos

**Comment by richard-ramos** [comment]
I tried to connect to those nodes and I end up with a timeout:
```
./build/waku --static-node=/ip4/134.209.134.63/tcp/9000/p2p/16Uiu2HAm9vnvCQgCDrynDK1h7GJoEZVGvnuzq84RyDQ3DEdXmcX7

2021-10-16T19:20:16.236-0400	INFO	wakunode	node/wakunode2.go:695	Setting up ping protocol with duration of 20s
2021-10-16T19:20:16.237-0400	INFO	wakunode	node/wakunode2.go:134	Listening on /ip4/192.168.1.19/tcp/9000/p2p/16Uiu2HAmSmoZsQUzAhn6MMJfkKCRiRiWimW6ZsV6pteQYSQfs8CZ
2021-10-16T19:20:16.237-0400	INFO	wakunode	node/wakunode2.go:134	Listening on /ip4/127.0.0.1/tcp/9000/p2p/16Uiu2HAmSmoZsQUzAhn6MMJfkKCRiRiWimW6ZsV6pteQYSQfs8CZ
2021-10-16T19:20:16.237-0400	INFO	wakurelay	relay/waku_relay.go:75	Relay protocol started
2021-10-16T19:20:21.238-0400	ERROR	wakunode	waku/node.go:193	error dialing peer failed to dial 16Uiu2HAm9vnvCQgCDrynDK1h7GJoEZVGvnuzq84RyDQ3DEdXmcX7:
  * [/ip4/134.209.134.63/tcp/9000] dial tcp4 0.0.0.0:9000->134.209.134.63:9000: i/o timeout

```

**Comment by richard-ramos** [comment]
> Any chance we could enable websocket too? I believe it's supported natively but not sure how SSL is handled.

It can be enabled with `--ws` flag.  WSS support is not supported unless you use a reverse proxy as described here: https://github.com/status-im/go-waku/issues/21#issuecomment-828039162

**Comment by richard-ramos** [comment]
A memory leak was fixed in this PR https://github.com/status-im/go-waku/pull/86. Once merged we should update the fleet

**Comment by jakubgs** [comment]
>I tried to connect to those nodes and I end up with a timeout:

@richard-ramos that's because I forgot to provide the `--port` flag when gen generating the multiaddress for Consul: https://github.com/status-im/infra-go-waku/commit/746d9641
```
 > curl -sSL fleets.status.im | jq '.fleets."go-waku.test"'
{
  "go-waku": {
    "node-01.ac-cn-hongkong-c.go-waku.test": "/ip4/8.218.2.110/tcp/30303/p2p/16Uiu2HAmBDbMWFiG9ki8sDw6fYtraSxo4oHU9HbuN43S2HVyq1FD",
    "node-01.do-ams3.go-waku.test": "/ip4/134.209.134.63/tcp/30303/p2p/16Uiu2HAm9vnvCQgCDrynDK1h7GJoEZVGvnuzq84RyDQ3DEdXmcX7",
    "node-01.gc-us-central1-a.go-waku.test": "/ip4/35.223.183.91/tcp/30303/p2p/16Uiu2HAmPz63Xc6AuVkDeujz7YeZta18rcdau3Y1BzaxKAfDrBqz"
  }
}
```

**Comment by jakubgs** [comment]
I can enable Websocket port, but for SSL I'd have to do some kind of LetsEncrypt setup similar to `infra-nim-waku`.

**Comment by jakubgs** [comment]
Here's the Certbot configuration that generates LetsEncrypt certificates and enables Websocket port: https://github.com/status-im/infra-go-waku/commit/6d8090bf
```
 > openssl s_client -connect node-01.do-ams3.go-waku.test.statusim.net:443 </dev/null 2>/dev/null | grep Subject  
subject=CN = node-01.do-ams3.go-waku.test.statusim.net
```
```
 > curl -sSL fleets.status.im | jq '.fleets."go-waku.test"'
{
  "libp2p": {
    "node-01.ac-cn-hongkong-c.go-waku.test": "/ip4/8.218.2.110/tcp/30303/p2p/16Uiu2HAmBDbMWFiG9ki8sDw6fYtraSxo4oHU9HbuN43S2HVyq1FD",
    "node-01.do-ams3.go-waku.test": "/ip4/134.209.134.63/tcp/30303/p2p/16Uiu2HAm9vnvCQgCDrynDK1h7GJoEZVGvnuzq84RyDQ3DEdXmcX7",
    "node-01.gc-us-central1-a.go-waku.test": "/ip4/35.223.183.91/tcp/30303/p2p/16Uiu2HAmPz63Xc6AuVkDeujz7YeZta18rcdau3Y1BzaxKAfDrBqz"
  },
  "websocket": {
    "node-01.ac-cn-hongkong-c.go-waku.test": "/dns4/node-01.ac-cn-hongkong-c.go-waku.test.statusim.net/tcp/443/wss/p2p/16Uiu2HAmBDbMWFiG9ki8sDw6fYtraSxo4oHU9HbuN43S2HVyq1FD",
    "node-01.do-ams3.go-waku.test": "/dns4/node-01.do-ams3.go-waku.test.statusim.net/tcp/443/wss/p2p/16Uiu2HAm9vnvCQgCDrynDK1h7GJoEZVGvnuzq84RyDQ3DEdXmcX7",
    "node-01.gc-us-central1-a.go-waku.test": "/dns4/node-01.gc-us-central1-a.go-waku.test.statusim.net/tcp/443/wss/p2p/16Uiu2HAmPz63Xc6AuVkDeujz7YeZta18rcdau3Y1BzaxKAfDrBqz"
  }
}
```
I renamed the service to be called `libp2p` to match the other one also being name of a protocol: https://github.com/status-im/infra-misc/commit/61364438

**Comment by jakubgs** [comment]
But it appears that the node won't start the Websocket port:
```
{"level":"info","ts":"2021-10-18T11:46:13.728Z","logger":"metrics","caller":"metrics/http.go:39","msg":"Starting server at  0.0.0.0:8008"}
{"level":"info","ts":"2021-10-18T11:46:13.832Z","logger":"wakunode","caller":"node/wakunode2.go:688","msg":"Setting up ping protocol with duration of 20s"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xdafba5]
goroutine 1 [running]:
github.com/status-im/go-waku/waku/v2/node.(*WakuNode).ListenAddresses(0xc0001d2700, 0x4a817c800, 0xc0001d2700, 0xc0003b38c0)
#011/app/waku/v2/node/wakunode2.go:232 +0x1a5
github.com/status-im/go-waku/waku/v2/node.New(0x1309380, 0xc00003a018, 0xc0003a6300, 0x8, 0xc, 0x0, 0x6, 0xc)
#011/app/waku/v2/node/wakunode2.go:133 +0x672
github.com/status-im/go-waku/waku.Execute(0x765f, 0xf4df5b, 0x7, 0x1, 0x2329, 0xf903e4, 0x7, 0x7ffebde0fbea, 0x40, 0xf9e2c6, ...)
#011/app/waku/node.go:166 +0x4f2
main.main()
#011/app/waku.go:26 +0xf8
```

**Comment by jakubgs** [comment]
Appears to be combination of `--ws` flag and `--advertise-address`. Opened an issue: https://github.com/status-im/go-waku/issues/89

**Comment by jakubgs** [comment]
Changed Docker tag used for `go-waku.test` fleet to be `deploy-test`: https://github.com/status-im/infra-go-waku/commit/01bdcd1b

**Comment by jakubgs** [comment]
With https://github.com/status-im/go-waku/pull/90 fix the Websocket port works fine:
```
admin@node-01.do-ams3.go-waku.test:~ % d inspect go-waku-node | jq -c '.[].NetworkSettings.Ports[] | values[] | {host: .HostIp, port: .HostPort}'
{"host":"0.0.0.0","port":"30303"}
{"host":"0.0.0.0","port":"8008"}
{"host":"0.0.0.0","port":"9001"}

admin@node-01.do-ams3.go-waku.test:~ % sudo netstat -lpnt | grep dockerd                                               
tcp        0      0 0.0.0.0:30303           0.0.0.0:*               LISTEN      775/dockerd         
tcp        0      0 0.0.0.0:8008            0.0.0.0:*               LISTEN      775/dockerd         
tcp        0      0 0.0.0.0:9001            0.0.0.0:*               LISTEN      775/dockerd      
```

**Comment by jakubgs** [comment]
I've added a `Jenkinsfile` for deploying new Docker images for the test fleet: https://github.com/status-im/go-waku/pull/107

**Comment by jakubgs** [comment]
I consider this done.
