### ISSUE TITLE
Connect go-waku test fleet with shards.test and bridge pubsub topics

### ISSUE THREAD

**Issue by richard-ramos** [status-im/infra-go-waku#14]
In https://github.com/waku-org/go-waku/pull/854 a feature to setup bridging for pubsub topics was introduced. This functionality is necessary because we're moving away from using the default pubsub topic and use instead a static shard: https://github.com/status-im/status-go/pull/4161

To avoid any potential disruption for messaging between different status-go, the following must be implemented:

1. go-waku test fleet must be updated to use @latest docker image. If necessary maybe we can do a release instead if you don't want to use latest
2. disable `--store` . It's not really being used, and we can avoid the problems we have run into with `VACUUM`
3. connect the go-waku test fleet with shards.test fleet
4. Add the following flags to go-waku to bridge the pubsub topics
```
--bridge-topics=/waku/2/default-waku/proto:/waku/2/rs/16/32 --bridge-topics=/waku/2/rs/16/32:/waku/2/default-waku/proto
```

**Comment by jakubgs** [comment]
Why is this issue overlapping with:

* https://github.com/status-im/infra-go-waku/issues/15

**Comment by richard-ramos** [comment]
I thought it would be good to have separate issues and PRs to track changes done on go-waku prod fleet and go-waku test fleet, but if it's an overkill, we can use a single issue instead. The only difference they have is that the go-waku test fleet should be connected to the shards.test fleet instead of the status.test fleet

**Comment by jakubgs** [comment]
I see, that makes sense then. Thanks for explaining.

**Comment by jakubgs** [comment]
Built current `master` for `test` fleet: https://ci.infra.status.im/job/go-waku/job/deploy-test/34/

**Comment by jakubgs** [comment]
I assume I can't just delete the SQLite database since there are tables other than `message` in it:
```
admin@node-01.do-ams3.go-waku.test:/docker/go-waku % sudo sqlite3 node/data/store.db '.schema' | grep CREATE
CREATE TABLE peerstore (key TEXT NOT NULL UNIQUE, data BYTEA);
CREATE TABLE gowaku_schema_migrations (version uint64,dirty bool);
CREATE TABLE message (
CREATE TABLE nonce (
CREATE TABLE registrations (
CREATE TABLE sqlite_sequence(name,seq);
CREATE UNIQUE INDEX version_unique ON gowaku_schema_migrations (version);
CREATE INDEX message_senderTimestamp ON message(senderTimestamp);
CREATE INDEX message_receiverTimestamp ON message(receiverTimestamp);
CREATE INDEX i_msg_1 ON message(contentTopic ASC, pubsubTopic ASC, senderTimestamp ASC, id ASC);
CREATE INDEX i_msg_2 ON message(contentTopic DESC, pubsubTopic DESC, senderTimestamp DESC, id DESC);
```
But does that mean `--store-message-db-url` flag is badly named and also affects storage of other non-storage related data?

**Comment by jakubgs** [comment]
Because currently if I disable the `store` protocol the `--store-message-db-url` flag will not be set:
```yaml
{% if go_waku_store_enabled %}
      --store-message-db-url=sqlite3:///data/store.db
      --store-message-retention-capacity={{ go_waku_store_capacity }}
      --store-message-retention-time={{ go_waku_store_duration }}
      --store-message-db-vacuum={{ go_waku_store_vacuum | bool | to_json }}
{% for node in go_waku_store_nodes %}
      --store-node={{ node }}
{% endfor %}
{% endif %}
```
https://github.com/status-im/infra-role-go-waku/blob/bd08b6d85422ae860a5fbaa77ca566ebd16ac435/templates/docker-compose.yml.j2#L45-L53

**Comment by jakubgs** [comment]
The help message states:
>`--store-message-db-url value`
>The database connection URL for persistent storage. (default: "sqlite3://store.db") [$WAKUNODE2_STORE_MESSAGE_DB_URL]

But then what does decide the location of for example `rendezvous` folder? I see no flag to configure that.

**Comment by jakubgs** [comment]
I can see that on `go-waku.prod` the store file is open:
```
admin@node-01.do-ams3.go-waku.prod:~ % d exec -it go-waku bash
root@27bc15ba0617:/# ls -l /proc/1/fd | grep store
lrwx------ 1 root root 64 Nov  8 14:16 3 -> /data/store.db
lrwx------ 1 root root 64 Nov  8 14:16 7 -> /data/store.db-wal
lrwx------ 1 root root 64 Nov  8 14:16 8 -> /data/store.db-shm
```
But after removing the `--store-*` flags from the `go-waku.test` nodes I see no such thing:
```
admin@node-01.do-ams3.go-waku.test:~ % d exec -it go-waku bash
root@710a2340916a:/# ls -l /proc/1/fd/ | grep store
root@710a2340916a:/# 
```
So what does that mean? That we no longer use the `peerstore` table and all peers are stored in memory?

**Comment by jakubgs** [comment]
Another problem is that if we want to connect this fleet to `shards.test` how can we do that considering we already use the `--dns-discovery-url` flag to allow the fleet nodes to connect to other nodes in the same fleet?
https://github.com/status-im/infra-go-waku/blob/c014a6630e141a823e81e1ba185d7f106420f9ea/ansible/group_vars/go-waku.yml#L17-L21

As far as I can tell the `--dns-discovery-url` flag can only be used once:

>`--dns-discovery-url value [ --dns-discovery-url value ]`
>URL for DNS node list in format 'enrtree://<key>@<fqdn>' [$WAKUNODE2_DNS_DISCOVERY_URL]

So how can I have the nodes connect to themselves within the fleet and also to `shards.test`?

**Comment by jakubgs** [comment]
Also, I can't seem to find any `--bridge-topic` flags in the image I built from `master`:
```
admin@node-01.do-ams3.go-waku.test:~ % d run --rm -it wakuorg/go-waku:deploy-test --version            
gowaku version 0.8.1-fab51bea
admin@node-01.do-ams3.go-waku.test:~ % d run --rm -it wakuorg/go-waku:deploy-test --help | grep bridge 
admin@node-01.do-ams3.go-waku.test:~ % 
```
Is it just missing from help?

**Comment by jakubgs** [comment]
So the summary of questions is:

- If `store` protocol is enabled the SQLite database is not used at all and can be removed?
- Is it possible to specify multiple ENTree URLs using `--dns-discovery-url` and if not how is this supposed to work?
- What decides the lcoation of the `rendezvous` folder?
- Is the `--bridge-topic` flag already in `master`?

**Comment by jakubgs** [comment]
I see, the `-bridge-topics`(notice the `s`) is hidden:
https://github.com/waku-org/go-waku/blob/fab51beadf681b81dcc8bb812289f9b2ca63ac1e/cmd/waku/flags.go#L267-L275

**Comment by richard-ramos** [comment]
> If `store` protocol is enabled the SQLite database is not used at all and can be removed?

yes. it can be removed

> Is it possible to specify multiple ENTree URLs using `--dns-discovery-url` and if not how is this supposed to work?

it is possible to specify multiple enrtrees, by repeating the `dns-discovery-url` flag

> What decides the lcoation of the rendezvous folder?

No idea what is this folder. What files does it have?

> Is the --bridge-topic flag already in master?

yes, it is hidden because this is supposed to be a flag used temporarily, and will be removed in future releases

**Comment by jakubgs** [comment]
Richard confirmed that `--dns-discovery-url` can be used multiple times, but the help message should be update to reflect that.

**Comment by jakubgs** [comment]
Changes:

- [`infra-role-go-waku#3d108fb6`](https://github.com/status-im/infra-role-go-waku/commit/3d108fb6) - docker: allow multiple uses of --dns-discovery-url
- [`infra-role-go-waku#e1bcfc2f`](https://github.com/status-im/infra-role-go-waku/commit/e1bcfc2f) - docker: add support for specifying extra flags
- [`infra-go-waku#3eea9f80`](https://github.com/status-im/infra-go-waku/commit/3eea9f80) - go-waku: disable store protocol
- [`infra-go-waku#fea681db`](https://github.com/status-im/infra-go-waku/commit/fea681db) - go-waku: add shards.test ENR, add bridge topics

Also fixed CI Docker build parameter defaults:

* https://github.com/waku-org/go-waku/pull/889
