### ISSUE TITLE
Setup pubsub topic bridging and disable store for go-waku prod fleet

### ISSUE THREAD

**Issue by richard-ramos** [status-im/infra-go-waku#15]
1. go-waku prod fleet must be updated to use @latest docker image. If necessary maybe we can do a release instead if you don't want to use latest
2. disable `--store` . It's not really being used, and we can avoid the problems we have run into with `VACUUM`
3. Add the following flags to go-waku to bridge the pubsub topics
```
--bridge-topic=/waku/2/default-waku/proto:/waku/2/rs/16/32 --bridge-topic=/waku/2/rs/16/32:/waku/2/default-waku/proto
```

**Comment by jakubgs** [comment]
Why is this issue overlapping with:

* https://github.com/status-im/infra-go-waku/issues/14

**Comment by jakubgs** [comment]
Changes:

- [`infra-role-go-waku#3d108fb6`](https://github.com/status-im/infra-role-go-waku/commit/3d108fb6) - docker: allow multiple uses of --dns-discovery-url
- [`infra-role-go-waku#e1bcfc2f`](https://github.com/status-im/infra-role-go-waku/commit/e1bcfc2f) - docker: add support for specifying extra flags
- [`infra-go-waku#3eea9f80`](https://github.com/status-im/infra-go-waku/commit/3eea9f80) - go-waku: disable store protocol
- [`infra-go-waku#fea681db`](https://github.com/status-im/infra-go-waku/commit/fea681db) - go-waku: add shards.test ENR, add bridge topics

Also fixed CI Docker build parameter defaults:

* https://github.com/waku-org/go-waku/pull/889
