### ISSUE TITLE
Update test and prod fleets to v0.9.0

### ISSUE THREAD

**Issue by richard-ramos** [status-im/infra-go-waku#16]
Docker Image: wakuorg/go-waku:v0.9.0

cc: @vitvly @cammellos @chaitanyaprem

**Comment by jakubgs** [comment]
Why can't you do it yourself?

* https://ci.infra.status.im/job/go-waku/job/deploy-test/
* https://ci.infra.status.im/job/go-waku/job/deploy-prod/

**Comment by richard-ramos** [comment]
Oops I forgot about those jobs! will do the deployment myself then!
thank you!

**Comment by jakubgs** [comment]
I see you ran the deployment jobs without issues:

![image](https://github.com/status-im/infra-go-waku/assets/2212681/7f5fd43e-9405-46dd-93dd-0ba9f3b4dc04)

![image](https://github.com/status-im/infra-go-waku/assets/2212681/0ea83d8b-fe12-4ebc-8437-0e71bebe735a)

Closing this.
