### ISSUE TITLE
Drop the go-waku fleets

### ISSUE THREAD

**Issue by richard-ramos** [status-im/infra-go-waku#18]
The following fleets are no longer necessary:
- go-waku.test
- go-waku.prod

cc: @chaitanyaprem, @fryorcraken

**Comment by jakubgs** [comment]
These fleets aren't really being widely used so no announcement or grace period should be required. It should be enough just to remove references from a few most important repositories:

- [x] https://github.com/waku-org/nwaku
- [x] https://github.com/waku-org/go-waku
- [x] https://github.com/waku-org/js-waku
- [x] https://github.com/waku-org/docs.waku.org
- [x] https://github.com/waku-org/waku-tests
- [x] https://github.com/status-im/status-go
- [x] https://github.com/status-im/status-mobile
- [x] https://github.com/status-im/status-desktop

**Comment by yakimant** [comment]
- [x] Check https://fleets.status.im cleaned up
- [ ] Archive this and role repos
- [x] Consul cleanup
- [x] Remove instances
- [x] Jenkins cleanup https://ci.infra.status.im/job/go-waku/job/deploy-test/ https://ci.infra.status.im/job/go-waku/job/deploy-prod/
- [x] infra-docs cleanup https://github.com/status-im/infra-docs/commit/c473b0af7c9b977633e8fbb45c7ffdf1c13fc623

**Comment by yakimant** [comment]
ENRs to search

- enr:-Ke4QExRcU9q8vpafzM7CDJT8i6izTXPvVTnhudE9CtnsQc8WJU1Fpzq8IxMiH6cX3Y6Hqxc4WUjpqTy8d2DOAd43e6GAYxFkWZwgmlkgnY0gmlwhIbRhj-CcnOLABAEAIABAAAgAECJc2VjcDI1NmsxoQLXeU4lGSJ1tZxRe52bZF68NIrqji8ld9f3-xIbjPxbPoN0Y3CCdl-DdWRwgiMohXdha3UyAQ
- enr:-Ke4QCdzv_hJ-MofGck6JnWfl8BMVat_TRW6tPsf5meGosTzHhQZgIfx3syYZ3Kri1RM35V3UxDub5PWnbxBP1_ny2SGAYxFlQGFgmlkgnY0gmlwhCPft1uCcnOLABAEAQAAIABAAICJc2VjcDI1NmsxoQOoVQePH5eRqlcCf-0XwZsoJPeZp1Mq59un_jYM9hUc6YN0Y3CCdl-DdWRwgiMohXdha3UyAQ
- enr:-Ke4QH5OS77duLmvpH-RZMaoZ-ATagcJdIbttDAsZo7TzBHuI6LN5dO2MmWstcR0KyrdLVvm16e7t1gecz6libHKX2CGAYxFlOsDgmlkgnY0gmlwhAjaAm6CcnOLABAEAEAAgAEAACCJc2VjcDI1NmsxoQLqosp15CMf5c4k-z9MGM7_aiR0DGdmSrpjQ_xWnmsTOIN0Y3CCdl-DdWRwgiMohXdha3UyAQ
- enr:-Ke4QExRcU9q8vpafzM7CDJT8i6izTXPvVTnhudE9CtnsQc8WJU1Fpzq8IxMiH6cX3Y6Hqxc4WUjpqTy8d2DOAd43e6GAYxFkWZwgmlkgnY0gmlwhIbRhj-CcnOLABAEAIABAAAgAECJc2VjcDI1NmsxoQLXeU4lGSJ1tZxRe52bZF68NIrqji8ld9f3-xIbjPxbPoN0Y3CCdl-DdWRwgiMohXdha3UyAQ
- enr:-Ke4QCdzv_hJ-MofGck6JnWfl8BMVat_TRW6tPsf5meGosTzHhQZgIfx3syYZ3Kri1RM35V3UxDub5PWnbxBP1_ny2SGAYxFlQGFgmlkgnY0gmlwhCPft1uCcnOLABAEAQAAIABAAICJc2VjcDI1NmsxoQOoVQePH5eRqlcCf-0XwZsoJPeZp1Mq59un_jYM9hUc6YN0Y3CCdl-DdWRwgiMohXdha3UyAQ
- enr:-Ke4QH5OS77duLmvpH-RZMaoZ-ATagcJdIbttDAsZo7TzBHuI6LN5dO2MmWstcR0KyrdLVvm16e7t1gecz6libHKX2CGAYxFlOsDgmlkgnY0gmlwhAjaAm6CcnOLABAEAEAAgAEAACCJc2VjcDI1NmsxoQLqosp15CMf5c4k-z9MGM7_aiR0DGdmSrpjQ_xWnmsTOIN0Y3CCdl-DdWRwgiMohXdha3UyAQ

Not found on GitHub

**Comment by yakimant** [comment]
For status-mobile need to update with
https://github.com/status-im/status-mobile/blob/4dded72878a4edc9140793e7ec0588e83e4a6c64/Makefile#L163-L166
after fleet is down.

**Comment by jakubgs** [comment]
You can just remove the fleet from the fleets script before the fleet is removed:
https://github.com/status-im/infra-misc/blob/da372af282cef6f0de2485bef34a2729ed5303e1/ansible/roles/status-fleets/files/eth_fleet_json.py#L128-L133

**Comment by yakimant** [comment]
Remove from status-fleets:
https://github.com/status-im/infra-misc/commit/d204c4beacc6d0fbde5da9835e856afc445cd49a

PR for status-mobile:
https://github.com/status-im/status-mobile/pull/18708

PR for status-desktop:
https://github.com/status-im/status-desktop/pull/13408

**Comment by yakimant** [comment]
@jakubgs, @richard-ramos, do you think we can decomission fleets before new versions of Status Desktop and Mobile are released (with fleets.json updated)?

Jakub kind of mentioned this already:
> These fleets aren't really being widely used so no announcement or grace period should be required.

Just double checking about the release.

**Comment by richard-ramos** [comment]
Yes, they can be decomissioned

**Comment by yakimant** [comment]
Also:
- [x] canary
- [x] metrics
- [ ] grafana
- [x] terraform state on Consul K/V

**Comment by yakimant** [comment]
Canaray and metrics cleanup:
https://github.com/status-im/infra-hq/commit/1cc0a2cbee034e3290ec270ba4a5ee8044b02776

**Comment by yakimant** [comment]
Cleaned up `/` and `/data` volumes on prod with `shred -vn 1 /dev/XXX`

**Comment by yakimant** [comment]
Grafana
- https://grafana.infra.status.im/d/CSLcLokVz/go-waku
- https://grafana.infra.status.im/dashboards/f/_vp9fMx4k/go-waku-experiments
- https://grafana.infra.status.im/d/4OZCs87Ik/go-waku
- https://grafana.infra.status.im/d/cBjKU8nIz/go-waku-test

Can we clean it?

**Comment by yakimant** [comment]
All done.

@jakubgs, @richard-ramos, please review and help to decide on Grafana dashboards.
Everything else looks done, will archive the repo after review.

**Comment by jakubgs** [comment]
I think it's fine to keep `go-waku` dashboards on Grafana, just to move them to some kind of `Archive` folder.

**Comment by jakubgs** [comment]
And remember to add a warning at the top of readme about this being a legacy repo, like so:
https://github.com/status-im/infra-avalanche

**Comment by yakimant** [comment]
All done, archiving.
