### ISSUE TITLE
Add a prod fleet

### ISSUE THREAD

**Issue by richard-ramos** [status-im/infra-go-waku#3]
- Fleet name: "go-waku.prod"
- Same configuration as "go-waku.test" except that the nodes will connect to wakuv2.prod instead of wakuv2.test
- Fleet size: same as test
- Purpose: Separate implementations of waku running in prod. CC: @John-44

**Comment by jakubgs** [comment]
Took this opportunity to refactor AlibabaCloud module a bit to use a `null_resource` for provisioning:

- https://github.com/status-im/infra-tf-alibaba-cloud/commit/ad94ffe8 - use null_resource to provision like other modules
- https://github.com/status-im/infra-tf-alibaba-cloud/commit/67812350 - fix provisioning by using EIP address

Also upgraded OS images used to Ubuntu `22.04`:

- https://github.com/status-im/infra-tf-digital-ocean/commit/57e0dd72 - upgrade image from Ubuntu 20.04 to 22.04
- https://github.com/status-im/infra-tf-alibaba-cloud/commit/c530eb79 - upgrade image from Ubuntu 20.04 to 22.04
- https://github.com/status-im/infra-tf-google-cloud/commit/a54afdd3 - upgrade image from Ubuntu 20.04 to 22.04

**Comment by jakubgs** [comment]
The fleet was created: https://github.com/status-im/infra-go-waku/commit/0e258e30
https://github.com/status-im/infra-go-waku/blob/0e258e307f89153dea6f578b79361de4b195c55a/ansible/inventory/prod#L4-L6

**Comment by jakubgs** [comment]
For now I've simply tagged `statusteam/go-waku:deploy-test` as `statusteam/go-waku:deploy-prod`.

**Comment by jakubgs** [comment]
I also updated the service names for `go-waku` to match `nim-waku` on https://fleets.status.im/:

- https://github.com/status-im/infra-misc/commit/16b3968d - status-fleets: fix go-waku service names

Result:
```
 > c fleets.status.im | jq '.fleets."go-waku.prod"."tcp/p2p/waku"'
{
  "node-01.ac-cn-hongkong-c.go-waku.prod": "/dns4/node-01.ac-cn-hongkong-c.go-waku.prod.statusim.net/tcp/30303/p2p/16Uiu2HAkwUKwy66nhcSFeW7y5qijNqXC4ZD3TaMMqnoEbh3wK2xU",
  "node-01.do-ams3.go-waku.prod": "/dns4/node-01.do-ams3.go-waku.prod.statusim.net/tcp/30303/p2p/16Uiu2HAkyScd7DiwgMwzfw8CFFhznH3wRzciqEUfjDzn7vyimR8c",
  "node-01.gc-us-central1-a.go-waku.prod": "/dns4/node-01.gc-us-central1-a.go-waku.prod.statusim.net/tcp/30303/p2p/16Uiu2HAmKTYnoPKebjWy63e1zPKiYRCQvm25W5mNSnCFE8EmzLga"
}
```
But I notice we've had websocket port disabled for a while now:
https://github.com/status-im/infra-go-waku/blob/0e258e307f89153dea6f578b79361de4b195c55a/ansible/group_vars/go-waku.yml#L23
Based on the commit it's waiting on this issue:

* https://github.com/status-im/go-waku/issues/275

If I remember correctly there was a port clash that could not be resolved due to a missing flag.
Was this ever fixed @richard-ramos?

**Comment by richard-ramos** [comment]
The issue is not fixed yet. Will be taken care of this week.

**Comment by jakubgs** [comment]
Fixed lack of service definition tho:

- https://github.com/status-im/infra-role-go-waku/commit/1897399b - consul: create service if just secure WS is enabled
- https://github.com/status-im/infra-go-waku/commit/a79b9431 - requirements: fix lack of websocket consul service

Now we get Websockets in https://fleets.status.im/:
```
 > c fleets.status.im | jq '.fleets."go-waku.prod"'
{
  "tcp/p2p/waku": {
    "node-01.ac-cn-hongkong-c.go-waku.prod": "/dns4/node-01.ac-cn-hongkong-c.go-waku.prod.statusim.net/tcp/30303/p2p/16Uiu2HAkwUKwy66nhcSFeW7y5qijNqXC4ZD3TaMMqnoEbh3wK2xU",
    "node-01.do-ams3.go-waku.prod": "/dns4/node-01.do-ams3.go-waku.prod.statusim.net/tcp/30303/p2p/16Uiu2HAkyScd7DiwgMwzfw8CFFhznH3wRzciqEUfjDzn7vyimR8c",
    "node-01.gc-us-central1-a.go-waku.prod": "/dns4/node-01.gc-us-central1-a.go-waku.prod.statusim.net/tcp/30303/p2p/16Uiu2HAmKTYnoPKebjWy63e1zPKiYRCQvm25W5mNSnCFE8EmzLga"
  },
  "wss/p2p/waku": {
    "node-01.ac-cn-hongkong-c.go-waku.prod": "/dns4/node-01.ac-cn-hongkong-c.go-waku.prod.statusim.net/tcp/443/wss/p2p/16Uiu2HAkwUKwy66nhcSFeW7y5qijNqXC4ZD3TaMMqnoEbh3wK2xU",
    "node-01.do-ams3.go-waku.prod": "/dns4/node-01.do-ams3.go-waku.prod.statusim.net/tcp/443/wss/p2p/16Uiu2HAkyScd7DiwgMwzfw8CFFhznH3wRzciqEUfjDzn7vyimR8c",
    "node-01.gc-us-central1-a.go-waku.prod": "/dns4/node-01.gc-us-central1-a.go-waku.prod.statusim.net/tcp/443/wss/p2p/16Uiu2HAmKTYnoPKebjWy63e1zPKiYRCQvm25W5mNSnCFE8EmzLga"
  }
}
```
Need anything else?
